"use client";
import React, { createContext, useContext, useState, ReactNode, useEffect } from "react";

export type Language = "vi" | "en" | "zh" | "es" | "fr" | "zh-TW" | "ko" | "ja" | "th" | "id";

interface Translations {
    [key: string]: string;
}

const dictionaries: Record<Language, Translations> = {
    vi: {
        loading: "Đang tải...", no_info: "Không tìm thấy thông tin nhà.", go_back: "Quay lại",
        available: "Đang cho thuê", rented: "Đã thuê", million: "triệu", vnd_per_month: "VNĐ / tháng",
        posted_by: "Đăng bởi", no_poster_info: "Chưa có thông tin người đăng", bedrooms: "Phòng ngủ",
        private_bath: "Khép kín", shared_bath: "Chung", bathrooms: "Phòng tắm", area: "Diện tích",
        description: "Mô tả chi tiết", no_description: "Chưa có mô tả chi tiết.", contact_now: "Liên hệ ngay",
        hello: "Xin chào", guest: "Khách", search_placeholder: "Tìm kiếm nhà thuê...", homepage: "Trang chủ", profile: "Hồ sơ",
        saved: "Đã lưu", my_listings: "Nhà của tôi", chats: "Chat",
        edit_profile: "Chỉnh sửa hồ sơ", display_name: "Tên hiển thị", bio: "Giới thiệu",
        change_limit: "Đổi tên 1 lần/30 ngày.", bio_placeholder: "Kể một chút về bản thân...",
        cancel: "Hủy", save_changes: "Lưu thay đổi", settings: "Cài đặt", accounts_center: "Trung tâm tài khoản",
        app_language: "Ngôn ngữ ứng dụng", help_support: "Trợ giúp & Hỗ trợ", about: "Giới thiệu", log_out: "Đăng xuất",
        uploading: "Đang tải lên...", edit_cover: "Sửa ảnh bìa", welcome_home: "Chào mừng về nhà",
        houses: "nhà", view_details: "Xem chi tiết →", month_abbr: "/tháng",
        add_property: "Thêm BĐS", property_type: "Loại hình", house: "Nhà phố", commercial_space: "Mặt bằng", apartment: "Căn hộ", condominium: "Chung cư", hotel: "Khách sạn", city: "Thành phố", district: "Quận/Huyện", address: "Địa chỉ cụ thể", exact_location: "Vị trí bản đồ", drag_pin: "Kéo thả ghim để chọn vị trí chính xác", price_vnd: "Giá (VNĐ)", area_m2: "Diện tích (m²)", contact_phone: "Số điện thoại", photos: "Hình ảnh", videos: "Video", upload: "Tải lên", click_add_photos: "Nhấn để thêm ảnh (tối đa 7)",
        click_add_videos: "Nhấn để thêm video (tối đa 2)",
        ward: "Phường/Xã",
        street_address: "Địa chỉ chi tiết (Số nhà, ngõ, tên đường)",
        use_current_location: "Sử dụng vị trí hiện tại",
        geocoding_loading: "Đang tìm vị trí...",
        submit_property: "Xác nhận đăng", submitting_property: "Đang xử lý...", submitted_success: "Đăng tin thành công", submitted_failed: "Đăng tin thất bại", try_again: "Thử lại", login_to_add: "Vui lòng đăng nhập để đăng tin", uploading_cloud: "Đang tải tệp lên máy chủ...",
        tour_step1_title: "Khám phá bất động sản trên trang chủ", tour_step1_desc: "Trang chủ hiển thị tất cả bất động sản cho thuê hiện có thông qua bản đồ trực quan.",
        tour_step2_title: "Điểm đánh dấu bất động sản", tour_step2_desc: "Mỗi điểm đánh dấu là một tin đăng. Nhấp để xem chi tiết.",
        tour_step3_title: "Thanh tìm kiếm", tour_step3_desc: "Dùng thanh tìm kiếm để tìm nhà theo địa điểm hoặc từ khoá.",
        tour_step4_title: "Bộ lọc", tour_step4_desc: "Lọc tin theo giá, loại hình hoặc các tiêu chí khác.",
        tour_step5_title: "Đăng tin mới", tour_step5_desc: "Nhấn đây để đăng tin cho thuê mới.",
        tour_done_title: "Bạn đã sẵn sàng! 🎉", tour_done_desc: "Hãy bắt đầu khám phá và đăng tin cho thuê ngay!",
        tour_skip: "Bỏ qua", tour_next: "Tiếp theo", tour_finish: "Bắt đầu",
        login_title: "Chào mừng trở lại",
        login_subtitle: "Đăng nhập để tiếp tục khám phá nhà thuê",
        email_username_placeholder: "Email hoặc tên đăng nhập",
        password_placeholder: "Mật khẩu",
        sign_in_btn: "Đăng nhập",
        signing_in: "Đang đăng nhập...",
        no_account: "Chưa có tài khoản?",
        create_one: "Tạo tài khoản ngay",
        register_title: "Tạo tài khoản của bạn",
        register_subtitle: "Tham gia cùng hàng ngàn người thuê nhà hạnh phúc",
        full_name_placeholder: "Họ và tên",
        username_placeholder: "Tên đăng nhập",
        email_placeholder: "Địa chỉ email",
        phone_placeholder: "Số điện thoại",
        confirm_password_placeholder: "Xác nhận mật khẩu",
        create_account_btn: "Tạo tài khoản",
        creating_account: "Đang tạo tài khoản...",
        already_have_account: "Đã có tài khoản?",
        sign_in_link: "Đăng nhập",
        hero_login_title: "Khám phá ngôi nhà thuê tiếp theo của bạn",
        hero_login_desc: "Duyệt hàng ngàn tin đăng đã xác thực, kết nối với chủ nhà và tìm không gian sống hoàn hảo.",
        hero_register_title: "Bắt đầu hành trình tìm kiếm ngôi nhà hoàn hảo",
        hero_register_desc: "Tạo tài khoản để lưu các tin đăng yêu thích, liên hệ trực tiếp với chủ nhà và nhận đề xuất cá nhân hóa.",
        logo_subtitle: "Tìm nơi ở hoàn hảo của bạn",
        err_enter_email_username: "Vui lòng nhập email hoặc tên đăng nhập",
        err_enter_password: "Vui lòng nhập mật khẩu",
        err_login_failed: "Đăng nhập thất bại. Vui lòng thử lại.",
        err_enter_full_name: "Vui lòng nhập họ và tên của bạn",
        err_enter_username: "Vui lòng nhập tên đăng nhập",
        err_username_length: "Tên đăng nhập phải có ít nhất 3 ký tự",
        err_enter_email: "Vui lòng nhập email của bạn",
        err_invalid_email: "Định dạng email không hợp lệ",
        err_enter_phone: "Vui lòng nhập số điện thoại",
        err_confirm_password: "Vui lòng xác nhận mật khẩu",
        err_passwords_mismatch: "Mật khẩu không khớp",
        err_complete_captcha: "Vui lòng hoàn thành mã captcha",
        password_requirements: "Yêu cầu mật khẩu:",
        rule_length: "8-12 ký tự",
        rule_uppercase: "Chữ hoa (A-Z)",
        rule_lowercase: "Chữ thường (a-z)",
        rule_number: "Chữ số (0-9)",
        rule_special: "Ký tự đặc biệt (@$!%*?&)",
        last_name: "Họ", first_name: "Tên", personal_info: "Thông tin cá nhân", security_settings: "Bảo mật & Mật khẩu",
        current_password: "Mật khẩu hiện tại", new_password: "Mật khẩu mới", confirm_new_password: "Xác nhận mật khẩu mới",
        update_password: "Cập nhật mật khẩu", email_label: "Địa chỉ Email", profile_updated_success: "Cập nhật hồ sơ thành công!",
        password_updated_success: "Đổi mật khẩu thành công!", account_privacy_title: "Tài khoản & Bảo mật",
        account_privacy_desc: "Quản lý thông tin cá nhân và cài đặt bảo mật của bạn tại đây.",
        help_title: "Trung tâm Hỗ trợ", help_subtitle: "Chúng tôi có thể giúp gì cho bạn?",
        faq_title: "Câu hỏi thường gặp", faq_q1: "Làm thế nào để đăng tin?", faq_a1: "Bạn chỉ cần nhấn nút + ở trang chủ hoặc trong hồ sơ.",
        contact_us: "Liên hệ chúng tôi", contact_email: "Gửi Email", contact_chat: "Chat trực tuyến", contact_call: "Gọi Hotline",
        profile_tab: "Cá nhân", post_listing_tab: "Đăng tin",
        saved_properties: "Bất động sản đã lưu", no_saved_properties: "Chưa có bất động sản đã lưu",
        save_properties_hint: "Nhấn vào biểu tượng trái tim trên bất kỳ tin đăng nào để lưu vào đây.",
        my_listings_title: "Tin đăng của tôi", no_listings_yet: "Chưa có tin đăng nào",
        add_listing_hint: "Sử dụng nút + ở phía dưới để thêm tin đăng đầu tiên của bạn.",
        display_mode: "Chế độ hiển thị", price: "Giá"
    },
    en: {
        loading: "Loading...", no_info: "Property information not found.", go_back: "Go back",
        available: "Available", rented: "Rented", million: "million", vnd_per_month: "VND / month",
        posted_by: "Posted by", no_poster_info: "No poster info", bedrooms: "Bedrooms",
        private_bath: "Private", shared_bath: "Shared", bathrooms: "Bathrooms", area: "Area",
        description: "Description", no_description: "No description available.", contact_now: "Contact Now",
        hello: "Hello", guest: "Guest", search_placeholder: "Search properties...", homepage: "Homepage", profile: "Profile",
        saved: "Saved", my_listings: "My Listings", chats: "Chats",
        edit_profile: "Edit Profile", display_name: "Display Name", bio: "Bio",
        change_limit: "Change limit: Once per 30 days.", bio_placeholder: "Tell us a bit about yourself...",
        cancel: "Cancel", save_changes: "Save Changes", settings: "Settings", accounts_center: "Accounts Center",
        app_language: "App Language", help_support: "Help & Support", about: "About", log_out: "Log Out",
        uploading: "Uploading...", edit_cover: "Edit Cover Image", welcome_home: "Welcome to Your Home",
        houses: "properties", view_details: "View details →", month_abbr: "/mo",
        add_property: "Add Property", property_type: "Property Type", house: "House", commercial_space: "Commercial Space", apartment: "Apartment", condominium: "Condominium", hotel: "Hotel", city: "City", district: "District", address: "Address", exact_location: "Exact Location", drag_pin: "Drag the pin to the exact property location", price_vnd: "Price (VND)", area_m2: "Area (m²)", contact_phone: "Contact Phone", photos: "Photos", videos: "Videos", upload: "Upload", click_add_photos: "Click to add photos (max 7)",
        click_add_videos: "Click to add videos (max 2)",
        ward: "Ward",
        street_address: "Street Address",
        use_current_location: "Use my current location",
        geocoding_loading: "Searching location...",
        submit_property: "Submit Property", submitting_property: "Submitting Property...", submitted_success: "Property submitted successfully", submitted_failed: "Property submitted failed", try_again: "Try Again", login_to_add: "Please log in to add a property", uploading_cloud: "Uploading media to Cloudinary...",
        tour_step1_title: "Discover Rentals on the Homepage", tour_step1_desc: "The homepage shows all rental properties currently available via our interactive map.",
        tour_step2_title: "Property Markers", tour_step2_desc: "Each marker represents a rental listing. Tap a marker to view details.",
        tour_step3_title: "Search Bar", tour_step3_desc: "Use the search bar to find rentals by location or keyword.",
        tour_step4_title: "Filters", tour_step4_desc: "Use filters to narrow down listings by price, type, or other criteria.",
        tour_step5_title: "Post a New Listing", tour_step5_desc: "Click here to post a new rental listing.",
        tour_done_title: "You're all set! 🎉", tour_done_desc: "You're ready to start exploring and posting rentals!",
        tour_skip: "Skip tour", tour_next: "Next", tour_finish: "Get Started",
        login_title: "Welcome back",
        login_subtitle: "Sign in to continue exploring rental homes",
        email_username_placeholder: "Email or username",
        password_placeholder: "Password",
        sign_in_btn: "Sign In",
        signing_in: "Signing in...",
        no_account: "Don't have an account?",
        create_one: "Create one",
        register_title: "Create your account",
        register_subtitle: "Join thousands of happy renters today",
        full_name_placeholder: "Full name",
        username_placeholder: "Username",
        email_placeholder: "Email address",
        phone_placeholder: "Phone number",
        confirm_password_placeholder: "Confirm password",
        create_account_btn: "Create Account",
        creating_account: "Creating account...",
        already_have_account: "Already have an account?",
        sign_in_link: "Sign in",
        hero_login_title: "Discover your next rental home",
        hero_login_desc: "Browse thousands of verified listings, connect with landlords, and find the perfect space that feels like home.",
        hero_register_title: "Start your journey to the perfect home",
        hero_register_desc: "Create an account to save your favorite listings, contact landlords directly, and receive personalized recommendations.",
        logo_subtitle: "Find your perfect place",
        err_enter_email_username: "Please enter your email or username",
        err_enter_password: "Please enter your password",
        err_login_failed: "Login failed. Please try again.",
        err_enter_full_name: "Please enter your full name",
        err_enter_username: "Please enter a username",
        err_username_length: "Username must be at least 3 characters",
        err_enter_email: "Please enter your email",
        err_invalid_email: "Invalid email format",
        err_enter_phone: "Please enter your phone number",
        err_confirm_password: "Please confirm your password",
        err_passwords_mismatch: "Passwords do not match",
        err_complete_captcha: "Please complete the captcha",
        password_requirements: "Password requirements:",
        rule_length: "8-12 characters",
        rule_uppercase: "Uppercase letter (A-Z)",
        rule_lowercase: "Lowercase letter (a-z)",
        rule_number: "Number (0-9)",
        rule_special: "Special character (@$!%*?&)",
        last_name: "Last Name", first_name: "First Name", personal_info: "Personal Information", security_settings: "Security & Password",
        current_password: "Current Password", new_password: "New Password", confirm_new_password: "Confirm New Password",
        update_password: "Update Password", email_label: "Email Address", profile_updated_success: "Profile updated successfully!",
        password_updated_success: "Password changed successfully!", account_privacy_title: "Account & Security",
        account_privacy_desc: "Manage your personal details and secure your account settings here.",
        help_title: "Help Center", help_subtitle: "How can we help you today?",
        faq_title: "Frequently Asked Questions", faq_q1: "How do I post a listing?", faq_a1: "Just click the + button on the home page or in your profile.",
        contact_us: "Contact Us", contact_email: "Email Support", contact_chat: "Live Chat", contact_call: "Call Hotline",
        profile_tab: "Profile", post_listing_tab: "Post Listing",
        saved_properties: "Saved Properties", no_saved_properties: "No saved properties",
        save_properties_hint: "Tap the heart icon on any property to save it here.",
        my_listings_title: "My Listings", no_listings_yet: "No listings yet",
        add_listing_hint: "Use the + button at the bottom to add your first property.",
        display_mode: "Display Mode", price: "Price"
    },
    zh: {
        loading: "加载中...", no_info: "未找到房产信息。", go_back: "返回",
        available: "可租", rented: "已租", million: "百万", vnd_per_month: "越南盾 / 月",
        posted_by: "发布者", no_poster_info: "无发布者信息", bedrooms: "卧室",
        private_bath: "独立", shared_bath: "共用", bathrooms: "浴室", area: "面积",
        description: "详细描述", no_description: "暂无描述。", contact_now: "立即联系",
        hello: "你好", guest: "游客", search_placeholder: "搜索房产...", homepage: "首页", profile: "简介",
        saved: "已保存", my_listings: "我的房源", chats: "聊天",
        edit_profile: "编辑简况", display_name: "显示名称", bio: "个人简介",
        change_limit: "更改限制：30天一次。", bio_placeholder: "介绍一下你自己...",
        cancel: "取消", save_changes: "保存更改", settings: "设置", accounts_center: "账户中心",
        app_language: "应用语言", help_support: "帮助与支持", about: "关于", log_out: "登出",
        uploading: "上传中...", edit_cover: "编辑封面图像", welcome_home: "欢迎回家",
        houses: "房产", view_details: "查看详情 →", month_abbr: "/月",
        add_property: "添加房产", property_type: "房产类型", house: "房屋", commercial_space: "商业空间", apartment: "公寓", condominium: "共管公寓", hotel: "酒店", city: "城市", district: "区县", address: "地址", exact_location: "精确位置", drag_pin: "拖动引脚到确切位置", price_vnd: "价格 (VND)", area_m2: "面积 (m²)", contact_phone: "联系电话", photos: "照片", videos: "视频", upload: "上传", click_add_photos: "点击添加照片(最多7张)",
        click_add_videos: "点击添加视频(最多2个)",
        ward: "镇/街道",
        street_address: "详细地址（门牌号、巷/弄，街道名称）",
        use_current_location: "使用当前位置",
        geocoding_loading: "正在搜索位置...",
        submit_property: "提交房产", submitting_property: "正在提交房产...", submitted_success: "房产提交成功", submitted_failed: "房产提交失败", try_again: "重试", login_to_add: "请登录后添加房产", uploading_cloud: "正在上传媒体上传...",
        tour_step1_title: "在地图上发现租房", tour_step1_desc: "地图显示所有当前可用的租赁房产。",
        tour_step2_title: "房产标记", tour_step2_desc: "每个标记代表一个租赁信息，点击可查看详情。",
        tour_step3_title: "搜索栏", tour_step3_desc: "使用搜索栏按地点或关键词查找租房。",
        tour_step4_title: "筛选器", tour_step4_desc: "按价格、类型或其他条件筛选房源。",
        tour_step5_title: "发布新房源", tour_step5_desc: "点击此处发布新的出租信息。",
        tour_done_title: "准备好了！🎉", tour_done_desc: "您已准备好开始浏览和发布租房信息！",
        tour_skip: "跳过", tour_next: "下一步", tour_finish: "开始",
        login_title: "欢迎回来",
        login_subtitle: "登录以继续探索房源",
        email_username_placeholder: "邮箱或用户名",
        password_placeholder: "密码",
        sign_in_btn: "登录",
        signing_in: "正在登录...",
        no_account: "没有账号？",
        create_one: "立即注册",
        register_title: "创建您的账号",
        register_subtitle: "加入数千名快乐的租客",
        full_name_placeholder: "全名",
        username_placeholder: "用户名",
        email_placeholder: "电子邮箱",
        phone_placeholder: "电话号码",
        confirm_password_placeholder: "确认密码",
        create_account_btn: "创建账号",
        creating_account: "正在创建...",
        already_have_account: "已有账号？",
        sign_in_link: "登录",
        hero_login_title: "发现您的下一个租房地点",
        hero_login_desc: "浏览数千个经过验证的房源，寻找像家一样的完美空间。",
        hero_register_title: "开启寻找完美家园之旅",
        hero_register_desc: "创建账号以保存收藏并获得推荐。",
        logo_subtitle: "找到您理想的住所",
        err_enter_email_username: "请输入邮箱或用户名",
        err_enter_password: "请输入密码",
        err_login_failed: "登录失败，请重试。",
        err_enter_full_name: "请输入您的全名",
        err_enter_username: "请输入用户名",
        err_username_length: "用户名至少3个字符",
        err_enter_email: "请输入您的邮箱",
        err_invalid_email: "邮箱格式不正确",
        err_enter_phone: "请输入电话号码",
        err_confirm_password: "请确认密码",
        err_passwords_mismatch: "密码不匹配",
        err_complete_captcha: "请完成验证码",
        password_requirements: "密码要求：",
        rule_length: "8-12个字符",
        rule_uppercase: "大写字母 (A-Z)",
        rule_lowercase: "小写字母 (a-z)",
        rule_number: "数字 (0-9)",
        rule_special: "特殊字符 (@$!%*?&)",
        last_name: "姓", first_name: "名", personal_info: "个人信息", security_settings: "安全与密码",
        current_password: "当前密码", new_password: "新密码", confirm_new_password: "确认新密码",
        update_password: "更新密码", email_label: "电子邮箱地址", profile_updated_success: "个人资料更新成功！",
        password_updated_success: "密码更改成功！", account_privacy_title: "账号与安全",
        account_privacy_desc: "在此管理您的个人详情并保护您的账号设置。",
        help_title: "帮助中心", help_subtitle: "今天我们能为您提供什么帮助？",
        faq_title: "常见问题", faq_q1: "如何发布房源？", faq_a1: "只需点击首页或个人资料中的 + 按钮。",
        contact_us: "联系我们", contact_email: "邮件支持", contact_chat: "在线聊天", contact_call: "拨打热线",
        profile_tab: "个人资料", post_listing_tab: "发布房源",
        saved_properties: "已保存的房产", no_saved_properties: "没有已保存的房产",
        save_properties_hint: "点击任何房产上的爱心图标将其保存在此处。",
        my_listings_title: "我的房源", no_listings_yet: "暂无房源",
        add_listing_hint: "使用底部的 + 按钮添加您的第一个房产。",
        display_mode: "显示模式", price: "价格"
    },
    es: {
        loading: "Cargando...", no_info: "Información de la propiedad no encontrada.", go_back: "Volver",
        available: "Disponible", rented: "Alquilado", million: "millones", vnd_per_month: "VND / mes",
        posted_by: "Publicado por", no_poster_info: "Sin información del anunciante", bedrooms: "Dormitorios",
        private_bath: "Privado", shared_bath: "Compartido", bathrooms: "Baños", area: "Área",
        description: "Descripción", no_description: "No hay descripción disponible.", contact_now: "Contactar ahora",
        hello: "Hola", guest: "Invitado", search_placeholder: "Buscar propiedades...", homepage: "Inicio", profile: "Perfil",
        saved: "Guardado", my_listings: "Mis Listados", chats: "Chats",
        edit_profile: "Editar Perfil", display_name: "Nombre visible", bio: "Biografía",
        change_limit: "Límite: Una vez cada 30 días.", bio_placeholder: "Cuéntanos un poco sobre ti...",
        cancel: "Cancelar", save_changes: "Guardar Cambios", settings: "Configuraciones", accounts_center: "Centro de Cuentas",
        app_language: "Idioma de la App", help_support: "Centro de Ayuda", about: "Acerca de", log_out: "Cerrar Sesión",
        uploading: "Subiendo...", edit_cover: "Editar imagen de portada", welcome_home: "Bienvenido a tu hogar",
        houses: "propiedades", view_details: "Ver detalles →", month_abbr: "/mes",
        add_property: "Añadir Propiedad", property_type: "Tipo de Propiedad", house: "Casa", commercial_space: "Local Comercial", apartment: "Apartamento", condominium: "Condominio", hotel: "Hotel", city: "Ciudad", district: "Distrito", address: "Dirección", exact_location: "Ubicación Exacta", drag_pin: "Arrastra el marcador a la ubicación exacta de la propiedad", price_vnd: "Precio (VND)", area_m2: "Área (m²)", contact_phone: "Teléfono de Contacto", photos: "Fotos", videos: "Videos", upload: "Subir", click_add_photos: "Haga clic para agregar fotos (máx. 7)",
        click_add_videos: "Haga clic para agregar videos (máx. 2)",
        ward: "Barrio/Comuna",
        street_address: "Dirección detallada (Número, calle, nombre de la calle)",
        use_current_location: "Usar mi ubicación actual",
        geocoding_loading: "Buscando ubicación...",
        submit_property: "Enviar P.", submitting_property: "Enviando...", submitted_success: "Propiedad enviada", submitted_failed: "Fallo al enviar", try_again: "Reintentar", login_to_add: "Inicie sesión para añadir", uploading_cloud: "Subiendo medios...",
        tour_step1_title: "Descubre Alquileres en el Mapa", tour_step1_desc: "Este mapa muestra todas las propiedades de alquiler disponibles.",
        tour_step2_title: "Marcadores de Propiedad", tour_step2_desc: "Cada marcador representa un listado. Toca un marcador para ver detalles.",
        tour_step3_title: "Barra de Búsqueda", tour_step3_desc: "Usa la barra de búsqueda para encontrar propiedades por ubicación.",
        tour_step4_title: "Filtros", tour_step4_desc: "Usa filtros para reducir los listados por precio, tipo, etc.",
        tour_step5_title: "Publicar un Nuevo Anuncio", tour_step5_desc: "Haz clic aquí para publicar un nuevo anuncio de alquiler.",
        tour_done_title: "¡Todo listo! 🎉", tour_done_desc: "¡Estás listo para explorar y publicar propiedades!",
        tour_skip: "Omitir", tour_next: "Siguiente", tour_finish: "Empezar",
        login_title: "Bienvenido de nuevo",
        login_subtitle: "Inicia sesión para continuar explorando casas",
        email_username_placeholder: "Correo o usuario",
        password_placeholder: "Contraseña",
        sign_in_btn: "Iniciar Sesión",
        signing_in: "Iniciando...",
        no_account: "¿No tienes cuenta?",
        create_one: "Crea una",
        register_title: "Crea tu cuenta",
        register_subtitle: "Únete a miles de inquilinos felices",
        full_name_placeholder: "Nombre completo",
        username_placeholder: "Usuario",
        email_placeholder: "Correo electrónico",
        phone_placeholder: "Teléfono",
        confirm_password_placeholder: "Confirmar contraseña",
        create_account_btn: "Crear Cuenta",
        creating_account: "Creando cuenta...",
        already_have_account: "¿Ya tienes cuenta?",
        sign_in_link: "Inicia sesión",
        hero_login_title: "Descubre tu próximo hogar",
        hero_login_desc: "Explora miles de anuncios verificados y encuentra el espacio perfecto que se sienta como en casa.",
        hero_register_title: "Comienza tu viaje hacia el hogar perfecto",
        hero_register_desc: "Crea una cuenta para guardar tus listados favoritos y contactar a los propietarios.",
        logo_subtitle: "Encuentra tu lugar ideal",
        err_enter_email_username: "Por favor ingrese su correo o usuario",
        err_enter_password: "Por favor ingrese su contraseña",
        err_login_failed: "Ingreso fallido. Intente de nuevo.",
        err_enter_full_name: "Por favor ingrese su nombre completo",
        err_enter_username: "Por favor ingrese un usuario",
        err_username_length: "El usuario debe tener al menos 3 caracteres",
        err_enter_email: "Por favor ingrese su correo",
        err_invalid_email: "Formato de correo inválido",
        err_enter_phone: "Por favor ingrese su teléfono",
        err_confirm_password: "Por favor confirme su contraseña",
        err_passwords_mismatch: "Las contraseñas no coinciden",
        err_complete_captcha: "Por favor complete el captcha",
        password_requirements: "Requisitos de contraseña:",
        rule_length: "8-12 caracteres",
        rule_uppercase: "Mayúscula (A-Z)",
        rule_lowercase: "Minúscula (a-z)",
        rule_number: "Número (0-9)",
        rule_special: "Especial (@$!%*?&)",
        last_name: "Apellido", first_name: "Nombre", personal_info: "Información personal", security_settings: "Seguridad y contraseña",
        current_password: "Contraseña actual", new_password: "Nueva contraseña", confirm_new_password: "Confirmar nueva contraseña",
        update_password: "Actualizar contraseña", email_label: "Correo electrónico", profile_updated_success: "¡Perfil actualizado con éxito!",
        password_updated_success: "¡Contraseña cambiada con éxito!", account_privacy_title: "Cuenta y seguridad",
        account_privacy_desc: "Administre sus datos personales y proteja la configuración de su cuenta aquí.",
        help_title: "Centro de ayuda", help_subtitle: "¿Cómo podemos ayudarte hoy?",
        faq_title: "Preguntas frecuentes", faq_q1: "¿Cómo publico un anuncio?", faq_a1: "Simplemente haz clic en el botón + en la página de inicio o en tu perfil.",
        contact_us: "Contáctenos", contact_email: "Soporte por correo", contact_chat: "Chat en vivo", contact_call: "Línea directa",
        profile_tab: "Perfil", post_listing_tab: "Publicar",
        saved_properties: "Propiedades guardadas", no_saved_properties: "No hay propiedades guardadas",
        save_properties_hint: "Toca el icono del corazón en cualquier propiedad para guardarla aquí.",
        my_listings_title: "Mis listados", no_listings_yet: "Aún no hay listados",
        add_listing_hint: "Usa el botón + en la parte inferior para añadir tu primera propiedad.",
        display_mode: "Modo de visualización", price: "Precio"
    },
    fr: {
        loading: "Chargement...", no_info: "Information non trouvée.", go_back: "Retour",
        available: "Disponible", rented: "Loué", million: "millions", vnd_per_month: "VND / mois",
        posted_by: "Posté par", no_poster_info: "Pas d'informations", bedrooms: "Chambres",
        private_bath: "Privée", shared_bath: "Partagée", bathrooms: "Salles de bain", area: "Surface",
        description: "Description", no_description: "Aucune description", contact_now: "Contacter",
        hello: "Bonjour", guest: "Invité", search_placeholder: "Rechercher...", homepage: "Accueil", profile: "Profil",
        saved: "Enregistré", my_listings: "Mes Annonces", chats: "Discussions",
        edit_profile: "Modifier le profil", display_name: "Nom d'affichage", bio: "Bio",
        change_limit: "Limite: Une fois tous les 30 jours.", bio_placeholder: "Parlez-nous de vous...",
        cancel: "Annuler", save_changes: "Enregistrer", settings: "Paramètres", accounts_center: "Espace Compte",
        app_language: "Langue", help_support: "Aide et Support", about: "À propos", log_out: "Se déconnecter",
        uploading: "Téléchargement...", edit_cover: "Modifier la couverture", welcome_home: "Bienvenue chez vous",
        houses: "propriétés", view_details: "Voir les détails →", month_abbr: "/mois",
        add_property: "Ajouter une propriété", property_type: "Type de propriété", house: "Maison", commercial_space: "Espace commercial", apartment: "Appartement", condominium: "Condominium", hotel: "Hôtel", city: "Ville", district: "District", address: "Adresse", exact_location: "Localisation exacte", drag_pin: "Faites glisser l'épingle vers l'emplacement exact de la propriété", price_vnd: "Prix (VND)", area_m2: "Surface (m²)", contact_phone: "Téléphone de contact", photos: "Photos", videos: "Vidéos", upload: "Télécharger", click_add_photos: "Cliquez pour ajouter des photos (max 7)",
        click_add_videos: "Cliquez pour ajouter des vidéos (max 2)",
        ward: "Quartier/Commune",
        street_address: "Adresse détaillée (Numéro, rue, nom de la rue)",
        use_current_location: "Utiliser ma position actuelle",
        geocoding_loading: "Recherche de l'emplacement...",
        submit_property: "Soumettre", submitting_property: "Soumission...", submitted_success: "Soumis avec succès", submitted_failed: "Échec de la soumission", try_again: "Réessayer", login_to_add: "Veuillez vous connecter", uploading_cloud: "Téléchargement...",
        tour_step1_title: "Découvrez les Locations sur la Carte", tour_step1_desc: "Cette carte montre toutes les propriétés disponibles.",
        tour_step2_title: "Marqueurs de Propriété", tour_step2_desc: "Chaque marqueur représente une annonce. Cliquez pour voir les détails.",
        tour_step3_title: "Barre de Recherche", tour_step3_desc: "Utilisez la barre de recherche pour trouver par lieu.",
        tour_step4_title: "Filtres", tour_step4_desc: "Utilisez les filtres pour affiner par prix, type, etc.",
        tour_step5_title: "Publier une Nouvelle Annonce", tour_step5_desc: "Cliquez ici pour publier une nouvelle annonce.",
        tour_done_title: "Tout est prêt ! 🎉", tour_done_desc: "Vous êtes prêt à explorer et publier des annonces !",
        tour_skip: "Passer", tour_next: "Suivant", tour_finish: "Commencer",
        login_title: "Bon retour",
        login_subtitle: "Connectez-vous pour continuer l'exploration",
        email_username_placeholder: "Email ou pseudo",
        password_placeholder: "Mot de passe",
        sign_in_btn: "Se connecter",
        signing_in: "Connexion...",
        no_account: "Pas de compte ?",
        create_one: "En créer un",
        register_title: "Créez votre compte",
        register_subtitle: "Rejoignez des milieux de locataires",
        full_name_placeholder: "Nom complet",
        username_placeholder: "Nom d'utilisateur",
        email_placeholder: "Adresse email",
        phone_placeholder: "Numéro de téléphone",
        confirm_password_placeholder: "Confirmer le mot de passe",
        create_account_btn: "Créer un compte",
        creating_account: "Création...",
        already_have_account: "Déjà un compte ?",
        sign_in_link: "Se connecter",
        hero_login_title: "Découvrez votre prochaine location",
        hero_login_desc: "Parcourez des milliers d'annonces vérifiées et trouvez l'espace idéal.",
        hero_register_title: "Commencez votre voyage vers le foyer idéal",
        hero_register_desc: "Créez un compte pour sauvegarder vos favoris.",
        logo_subtitle: "Trouvez votre lieu idéal",
        err_enter_email_username: "Veuillez entrer votre email ou pseudo",
        err_enter_password: "Veuillez entrer votre mot de passe",
        err_login_failed: "Échec de connexion. Réessayez.",
        err_enter_full_name: "Veuillez entrer votre nom complet",
        err_enter_username: "Veuillez entrer un pseudo",
        err_username_length: "Le pseudo doit faire au moins 3 caractères",
        err_enter_email: "Veuillez entrer votre email",
        err_invalid_email: "Format d'email invalide",
        err_enter_phone: "Veuillez entrer votre numéro de téléphone",
        err_confirm_password: "Veuillez confirmer votre mot de passe",
        err_passwords_mismatch: "Les mots de passe ne correspondent pas",
        err_complete_captcha: "Veuillez compléter le captcha",
        password_requirements: "Exigences du mot de passe :",
        rule_length: "8-12 caractères",
        rule_uppercase: "Majuscule (A-Z)",
        rule_lowercase: "Minuscule (a-z)",
        rule_number: "Chiffre (0-9)",
        rule_special: "Spécial (@$!%*?&)",
        last_name: "Nom", first_name: "Prénom", personal_info: "Informations personnelles", security_settings: "Sécurité et mot de passe",
        current_password: "Mot de passe actuel", new_password: "Nouveau mot de passe", confirm_new_password: "Confirmer le nouveau mot de passe",
        update_password: "Mettre à jour le mot de passe", email_label: "Adresse e-mail", profile_updated_success: "Profil mis à jour avec succès !",
        password_updated_success: "Mot de passe changé avec succès !", account_privacy_title: "Compte et sécurité",
        account_privacy_desc: "Gérez vos informations personnelles et sécurisez vos paramètres de compte ici.",
        help_title: "Centre d'aide", help_subtitle: "Comment pouvons-nous vous aider aujourd'hui ?",
        faq_title: "Questions fréquemment posées", faq_q1: "Comment puis-je publier une annonce ?", faq_a1: "Il suffit de cliquer sur le bouton + sur la page d'accueil ou dans votre profil.",
        contact_us: "Contactez-nous", contact_email: "Support par e-mail", contact_chat: "Chat en direct", contact_call: "Ligne directe",
        profile_tab: "Profil", post_listing_tab: "Publier",
        saved_properties: "Propriétés enregistrées", no_saved_properties: "Aucune propriété enregistrée",
        save_properties_hint: "Appuyez sur l'icône du cœur sur n'importe quelle annonce pour l'enregistrer ici.",
        my_listings_title: "Mes annonces", no_listings_yet: "Pas encore d'annonces",
        add_listing_hint: "Utilisez le bouton + en bas pour ajouter votre première propriété.",
        display_mode: "Mode d'affichage", price: "Prix"
    },
    "zh-TW": {
        loading: "載入中...", no_info: "未找到房產資訊。", go_back: "返回",
        available: "可租", rented: "已租", million: "百萬", vnd_per_month: "越南盾 / 月",
        posted_by: "發布者", no_poster_info: "無發布者資訊", bedrooms: "臥室",
        private_bath: "獨立", shared_bath: "共用", bathrooms: "浴室", area: "面積",
        description: "詳細描述", no_description: "暫無描述。", contact_now: "立即聯繫",
        hello: "你好", guest: "遊客", search_placeholder: "搜索房產...", homepage: "首頁", profile: "簡介",
        saved: "已保存", my_listings: "我的房源", chats: "聊天",
        edit_profile: "編輯簡況", display_name: "顯示名稱", bio: "個人簡介",
        change_limit: "更改限制：30天一次。", bio_placeholder: "介紹一下你自己...",
        cancel: "取消", save_changes: "保存更改", settings: "設置", accounts_center: "帳戶中心",
        app_language: "應用語言", help_support: "幫助與支持", about: "關於", log_out: "登出",
        uploading: "上傳中...", edit_cover: "編輯封面圖像", welcome_home: "歡迎回家",
        houses: "房產", view_details: "查看詳情 →", month_abbr: "/月",
        add_property: "添加房產", property_type: "房產類型", house: "房屋", commercial_space: "商業空間", apartment: "公寓", condominium: "共管公寓", hotel: "酒店", city: "城市", district: "區縣", address: "地址", exact_location: "精確位置", drag_pin: "拖動引腳到確切位置", price_vnd: "價格 (VND)", area_m2: "面積 (m²)", contact_phone: "聯繫電話", photos: "照片", videos: "視頻", upload: "上傳", click_add_photos: "點擊添加照片(最多7張)",
        click_add_videos: "點擊添加視頻(最多2個)",
        ward: "鎮/街道",
        street_address: "詳細地址（門牌號、巷/弄，街道名稱）",
        use_current_location: "使用當前位置",
        geocoding_loading: "正在搜索位置...",
        submit_property: "提交房產", submitting_property: "正在提交房產...", submitted_success: "房產提交成功", submitted_failed: "房產提交失敗", try_again: "重試", login_to_add: "請登錄後添加房產", uploading_cloud: "正在上傳媒體上傳...",
        tour_step1_title: "在地圖上發現租房", tour_step1_desc: "地圖顯示所有當前可用的租賃房產。",
        tour_step2_title: "房產標記", tour_step2_desc: "每個標記代表一個租賃信息，點擊可查看詳情。",
        tour_step3_title: "搜索欄", tour_step3_desc: "使用搜索欄按地點或關鍵詞查找租房。",
        tour_step4_title: "篩選器", tour_step4_desc: "按價格、類型或其他條件篩選房源。",
        tour_step5_title: "發布新房源", tour_step5_desc: "點擊此處發布新的出租信息。",
        tour_done_title: "準備好了！🎉", tour_done_desc: "您已準備好開始瀏覽和發布租房信息！",
        tour_skip: "跳過", tour_next: "下一步", tour_finish: "開始",
        login_title: "歡迎回來",
        login_subtitle: "登錄以繼續探索房源",
        email_username_placeholder: "電子郵件或用戶名",
        password_placeholder: "密碼",
        sign_in_btn: "登錄",
        signing_in: "正在登錄...",
        no_account: "沒有賬號？",
        create_one: "立即註冊",
        register_title: "創建您的賬號",
        register_subtitle: "加入數千名快樂的租客",
        full_name_placeholder: "全名",
        username_placeholder: "用戶名",
        email_placeholder: "電子郵件地址",
        phone_placeholder: "電話號碼",
        confirm_password_placeholder: "確認密碼",
        create_account_btn: "創建賬號",
        creating_account: "正在創建...",
        already_have_account: "已有賬號？",
        sign_in_link: "登錄",
        hero_login_title: "發現您的下一個租房地點",
        hero_login_desc: "瀏覽數千個經過驗證的房源，尋找像家一樣的完美空間。",
        hero_register_title: "開啟尋找完美家園之旅",
        hero_register_desc: "創建賬號以保存收藏並獲得推薦。",
        logo_subtitle: "找到您理想的住所",
        err_enter_email_username: "請輸入電子郵件或用戶名",
        err_enter_password: "請輸入密碼",
        err_login_failed: "登錄失敗，請重試。",
        err_enter_full_name: "請輸入您的全名",
        err_enter_username: "請輸入用戶名",
        err_username_length: "用戶名至少3個字符",
        err_enter_email: "請輸入您的電子郵件",
        err_invalid_email: "電子郵件格式不正確",
        err_enter_phone: "請輸入電話號碼",
        err_confirm_password: "請確認密碼",
        err_passwords_mismatch: "密碼不匹配",
        err_complete_captcha: "請完成驗證碼",
        password_requirements: "密碼要求：",
        rule_length: "8-12個字符",
        rule_uppercase: "大写字母 (A-Z)",
        rule_lowercase: "小写字母 (a-z)",
        rule_number: "数字 (0-9)",
        rule_special: "特殊字符 (@$!%*?&)",
        last_name: "姓", first_name: "名", personal_info: "個人信息", security_settings: "安全與密碼",
        current_password: "當前密碼", new_password: "新密碼", confirm_new_password: "確認新密碼",
        update_password: "更新密碼", email_label: "電子郵件地址", profile_updated_success: "個人資料更新成功！",
        password_updated_success: "密碼更改成功！", account_privacy_title: "賬號與安全",
        account_privacy_desc: "在此管理您的個人詳情並保護您的賬號設置。",
        help_title: "幫助中心", help_subtitle: "今天我們能为您提供什麼幫助？",
        faq_title: "常見問題", faq_q1: "如何發布房源？", faq_a1: "只需點擊首頁或個人資料中的 + 按鈕。",
        contact_us: "聯繫我們", contact_email: "郵件支持", contact_chat: "在線聊天", contact_call: "撥打熱線",
        profile_tab: "個人資料", post_listing_tab: "發布房源",
        saved_properties: "已保存的房產", no_saved_properties: "沒有已保存的房產",
        save_properties_hint: "點擊任何房產上的愛心圖標將其保存在此處。",
        my_listings_title: "我的房源", no_listings_yet: "暫無房源",
        add_listing_hint: "使用底部的 + 按鈕添加您的第一個房產。",
        display_mode: "顯示模式", price: "價格"
    },
    ko: {
        loading: "로딩 중...", no_info: "정보를 찾을 수 없습니다.", go_back: "뒤로",
        available: "이용 가능", rented: "임대됨", million: "백만", vnd_per_month: "VND / 월",
        posted_by: "게시자", no_poster_info: "게시자 정보 없음", bedrooms: "침실",
        private_bath: "개별", shared_bath: "공용", bathrooms: "욕실", area: "면적",
        description: "설명", no_description: "설명 없음", contact_now: "연락하기",
        hello: "안녕하세요", guest: "게스트", search_placeholder: "검색...", homepage: "홈페이지", profile: "프로필",
        saved: "저장됨", my_listings: "내 숙소", chats: "채팅",
        edit_profile: "프로필 편집", display_name: "표시 이름", bio: "소개",
        change_limit: "변경 제한: 30일마다 한 번.", bio_placeholder: "자기소개를 입력하세요...",
        cancel: "취소", save_changes: "변경 사항 저장", settings: "설정", accounts_center: "계정 센터",
        app_language: "앱 언어", help_support: "도움말 및 지원", about: "정보", log_out: "로그아웃",
        uploading: "업로드 중...", edit_cover: "커버 이미지 편집", welcome_home: "환영합니다",
        houses: "숙소", view_details: "세부 정보 보기 →", month_abbr: "/월",
        add_property: "숙소 추가", property_type: "숙소 유형", house: "주택", commercial_space: "상업 공간", apartment: "아파트", condominium: "콘도미니엄", hotel: "호텔", city: "도시", district: "구/군", address: "주소", exact_location: "정확한 위치", drag_pin: "정확한 숙소 위치로 핀을 드래그하세요", price_vnd: "가격 (VND)", area_m2: "면적 (m²)", contact_phone: "연락처", photos: "사진", videos: "동영상", upload: "업로드", click_add_photos: "사진을 추가하려면 클릭하세요 (최대 7개)",
        click_add_videos: "동영상을 추가하려면 클릭하세요 (최대 2개)",
        ward: "동/읍/면",
        street_address: "상세 주소 (번지, 골목, 도로명)",
        use_current_location: "내 현재 위치 사용",
        geocoding_loading: "위치 검색 중...",
        submit_property: "숙소 등록", submitting_property: "처리 중...", submitted_success: "성공적으로 제출됨", submitted_failed: "제출 실패", try_again: "다시 시도", login_to_add: "추가하려면 로그인하세요.", uploading_cloud: "업로드 중...",
        tour_step1_title: "지도에서 렌탈 발견", tour_step1_desc: "이 지도는 현재 이용 가능한 모든 임대 숙소를 보여줍니다.",
        tour_step2_title: "숙소 마커", tour_step2_desc: "각 마커는 숙소를 나타냅니다. 마커를 탭하여 세부 정보를 확인하세요.",
        tour_step3_title: "검색 창", tour_step3_desc: "검색 창을 사용하여 위치로 숙소를 찾으세요.",
        tour_step4_title: "필터", tour_step4_desc: "가격, 유형 등으로 숙소를 필터링하세요.",
        tour_step5_title: "새 숙소 게시", tour_step5_desc: "여기를 클릭하여 새 임대 숙소를 게시하세요.",
        tour_done_title: "완료되었습니다! 🎉", tour_done_desc: "숙소를 탐색하고 게시할 준비가 되었습니다!",
        tour_skip: "건너뛰기", tour_next: "다음", tour_finish: "시작하기",
        login_title: "환영합니다",
        login_subtitle: "계속해서 숙소를 둘러보려면 로그인하세요",
        email_username_placeholder: "이메일 또는 아이디",
        password_placeholder: "비밀번호",
        sign_in_btn: "로그인",
        signing_in: "로그인 중...",
        no_account: "계정이 없으신가요?",
        create_one: "계정 만들기",
        register_title: "계정 생성",
        register_subtitle: "수천 명의 행복한 세입자와 함께하세요",
        full_name_placeholder: "이름",
        username_placeholder: "사용자 이름",
        email_placeholder: "이메일 주소",
        phone_placeholder: "전화번호",
        confirm_password_placeholder: "비밀번호 확인",
        create_account_btn: "계정 만들기",
        creating_account: "생성 중...",
        already_have_account: "이미 계정이 있나요?",
        sign_in_link: "로그인",
        hero_login_title: "다음 렌탈 홈을 발견하세요",
        hero_login_desc: "인증된 수천 개의 매물을 찾아보세요.",
        hero_register_title: "완벽한 집을 향한 여정을 시작하세요",
        hero_register_desc: "계정을 만들어 즐겨찾기를 저장하세요.",
        logo_subtitle: "완벽한 장소를 찾으세요",
        err_enter_email_username: "이메일 또는 아이디를 입력하세요",
        err_enter_password: "비밀번호를 입력하세요",
        err_login_failed: "로그인 실패. 다시 시도하십시오.",
        err_enter_full_name: "이름을 입력하세요",
        err_enter_username: "사용자 이름을 입력하세요",
        err_username_length: "아이디는 3자 이상이어야 합니다",
        err_enter_email: "이메일을 입력하세요",
        err_invalid_email: "잘못된 이메일 형식",
        err_enter_phone: "전화번호를 입력하세요",
        err_confirm_password: "비밀번호를 다시 입력하세요",
        err_passwords_mismatch: "비밀번호가 일치하지 않습니다",
        err_complete_captcha: "캡차를 완료하세요",
        password_requirements: "비밀번호 요구사항:",
        rule_length: "8-12자",
        rule_uppercase: "대문자 (A-Z)",
        rule_lowercase: "소문자 (a-z)",
        rule_number: "숫자 (0-9)",
        rule_special: "특수 문자 (@$!%*?&)",
        last_name: "성", first_name: "이름", personal_info: "개인 정보", security_settings: "보안 및 비밀번호",
        current_password: "현재 비밀번호", new_password: "새 비밀번호", confirm_new_password: "새 비밀번호 확인",
        update_password: "비밀번호 업데이트", email_label: "이메일 주소", profile_updated_success: "프로필이 업데이트되었습니다!",
        password_updated_success: "비밀번호가 성공적으로 변경되었습니다!", account_privacy_title: "계정 및 보안",
        account_privacy_desc: "여기에서 개인 정보 및 보안 설정을 관리하세요.",
        help_title: "고객 센터", help_subtitle: "무엇을 도와드릴까요?",
        faq_title: "자주 묻는 질문", faq_q1: "매물을 어떻게 게시하나요?", faq_a1: "홈페이지 또는 프로필에 있는 + 버튼을 누르시면 됩니다.",
        contact_us: "문의하기", contact_email: "이메일 지원", contact_chat: "실시간 채팅", contact_call: "고객 센터 전화",
        profile_tab: "프로필", post_listing_tab: "등록",
        saved_properties: "저장된 숙소", no_saved_properties: "저장된 숙소가 없습니다",
        save_properties_hint: "숙소의 하트 아이콘을 눌러 여기에 저장하세요.",
        my_listings_title: "내 숙소", no_listings_yet: "아직 숙소가 없습니다",
        add_listing_hint: "하단의 + 버튼을 사용하여 첫 숙소를 추가하세요.",
        display_mode: "표시 모드", price: "가격"
    },
    ja: {
        loading: "読み込み中...", no_info: "物件情報が見つかりません。", go_back: "戻る",
        available: "空室", rented: "成約済み", million: "百万", vnd_per_month: "VND / 月",
        posted_by: "投稿者", no_poster_info: "投稿者情報なし", bedrooms: "寝室",
        private_bath: "専用", shared_bath: "共用", bathrooms: "浴室", area: "面積",
        description: "詳細説明", no_description: "説明はありません。", contact_now: "お問い合わせ",
        hello: "こんにちは", guest: "ゲスト", search_placeholder: "物件を検索...", homepage: "ホームページ", profile: "プロフィール",
        saved: "保存済み", my_listings: "マイ物件", chats: "チャット",
        edit_profile: "プロフィール編集", display_name: "表示名", bio: "自己紹介",
        change_limit: "変更制限：30日に1回。", bio_placeholder: "自己紹介を書いてください...",
        cancel: "キャンセル", save_changes: "変更を保存", settings: "設定", accounts_center: "アカウントセンター",
        app_language: "アプリの言語", help_support: "ヘルプとサポート", about: "情報", log_out: "ログアウト",
        uploading: "アップロード中...", edit_cover: "カバー画像を編集", welcome_home: "おかえりなさい",
        houses: "物件", view_details: "詳細を見る →", month_abbr: "/月",
        add_property: "物件を追加", property_type: "物件タイプ", house: "一戸建て", commercial_space: "店舗・事務所", apartment: "アパート", condominium: "マンション", hotel: "ホテル", city: "都市", district: "区・郡", address: "住所", exact_location: "正確な位置", drag_pin: "ピンを正確な位置にドラッグしてください", price_vnd: "価格 (VND)", area_m2: "面積 (m²)", contact_phone: "電話番号", photos: "写真", videos: "動画", upload: "アップロード", click_add_photos: "クリックして写真を追加 (最大7枚)",
        click_add_videos: "クリックして動画を追加 (最大2本)",
        ward: "街区",
        street_address: "詳細住所（番地、号、通り名）",
        use_current_location: "現在地を使用",
        geocoding_loading: "位置を検索中...",
        submit_property: "物件を登録", submitting_property: "登録中...", submitted_success: "登録に成功しました", submitted_failed: "登録に失敗しました", try_again: "再試行", login_to_add: "ログインして追加してください", uploading_cloud: "メディアをアップロード中...",
        tour_step1_title: "地図で賃貸を探す", tour_step1_desc: "ホームページでは、対話型地図を通じて現在利用可能なすべての賃貸物件を表示します。",
        tour_step2_title: "物件マーカー", tour_step2_desc: "各マーカーは賃貸物件を表します。マーカーをタップして詳細を表示します。",
        tour_step3_title: "検索バー", tour_step3_desc: "検索バーを使用して、場所やキーワードで賃貸を検索します。",
        tour_step4_title: "フィルター", tour_step4_desc: "フィルターを使用して、価格やタイプなどで物件を絞り込みます。",
        tour_step5_title: "新しい物件を投稿", tour_step5_desc: "ここをクリックして新しい賃貸物件を投稿します。",
        tour_done_title: "準備完了！🎉", tour_done_desc: "探索と投稿の準備ができました！",
        tour_skip: "スキップ", tour_next: "次へ", tour_finish: "始める",
        login_title: "おかえりなさい",
        login_subtitle: "続行するにはログインしてください",
        email_username_placeholder: "メールまたはユーザー名",
        password_placeholder: "パスワード",
        sign_in_btn: "ログイン",
        signing_in: "ログイン中...",
        no_account: "アカウントをお持ちでないですか？",
        create_one: "アカウント作成",
        register_title: "アカウントを作成",
        register_subtitle: "ハッピーな入居者の仲間入りをしましょう",
        full_name_placeholder: "氏名",
        username_placeholder: "ユーザー名",
        email_placeholder: "メールアドレス",
        phone_placeholder: "電話番号",
        confirm_password_placeholder: "パスワードを再入力",
        create_account_btn: "アカウント作成",
        creating_account: "作成中...",
        already_have_account: "既にアカウントをお持ちですか？",
        sign_in_link: "ログイン",
        hero_login_title: "次の賃貸住宅を見つけよう",
        hero_login_desc: "確認済みの何千もの物件を閲覧し、理想の住まいを見つけましょう。",
        hero_register_title: "理想の住まいへの旅を始めましょう",
        hero_register_desc: "アカウントを作成して、お気に入りの物件を保存しましょう。",
        logo_subtitle: "理想の場所を見つける",
        err_enter_email_username: "メールまたはユーザー名を入力してください",
        err_enter_password: "パスワードを入力してください",
        err_login_failed: "ログインに失敗しました。もう一度お試しください。",
        err_enter_full_name: "氏名を入力してください",
        err_enter_username: "ユーザー名を入力してください",
        err_username_length: "ユーザー名は3文字以上である必要があります",
        err_enter_email: "メールアドレスを入力してください",
        err_invalid_email: "無効なメール形式です",
        err_enter_phone: "電話番号を入力してください",
        err_confirm_password: "パスワードを再入力してください",
        err_passwords_mismatch: "パスワードが一致しません",
        err_complete_captcha: "画像認証を完了してください",
        password_requirements: "パスワードの要件：",
        rule_length: "8-12文字",
        rule_uppercase: "大文字 (A-Z)",
        rule_lowercase: "小文字 (a-z)",
        rule_number: "数字 (0-9)",
        rule_special: "特殊文字 (@$!%*?&)",
        last_name: "姓", first_name: "名", personal_info: "個人情報", security_settings: "セキュリティとパスワード",
        current_password: "現在のパスワード", new_password: "新しいパスワード", confirm_new_password: "新しいパスワードを再入力",
        update_password: "パスワードを更新", email_label: "メールアドレス", profile_updated_success: "プロフィールの更新に成功しました！",
        password_updated_success: "パスワードの変更に成功しました！", account_privacy_title: "アカウントとセキュリティ",
        account_privacy_desc: "ここで個人情報の管理とセキュリティ設定を行います。",
        help_title: "ヘルプセンター", help_subtitle: "何かお手伝いしましょうか？",
        faq_title: "よくある質問", faq_q1: "物件を投稿するには？", faq_a1: "ホームページまたはプロフィールの + ボタンをクリックしてください。",
        contact_us: "お問い合わせ", contact_email: "メールサポート", contact_chat: "ライブチャット", contact_call: "ホットライン",
        profile_tab: "プロフィール", post_listing_tab: "投稿",
        saved_properties: "保存した物件", no_saved_properties: "保存した物件はありません",
        save_properties_hint: "物件のハートアイコンをタップして保存します。",
        my_listings_title: "マイ物件", no_listings_yet: "物件はまだありません",
        add_listing_hint: "下の + ボタンから最初の物件を追加しましょう。",
        display_mode: "表示モード", price: "価格"
    },
    th: {
        loading: "กำลังโหลด...", no_info: "ไม่พบข้อมูลที่พัก", go_back: "ย้อนกลับ",
        available: "พร้อมเช่า", rented: "เช่าแล้ว", million: "ล้าน", vnd_per_month: "VND / เดือน",
        posted_by: "โพสต์โดย", no_poster_info: "ไม่มีข้อมูลผู้โพสต์", bedrooms: "ห้องนอน",
        private_bath: "ส่วนตัว", shared_bath: "รวม", bathrooms: "ห้องน้ำ", area: "พื้นที่",
        description: "รายละเอียด", no_description: "ไม่มีรายละเอียด", contact_now: "ติดต่อตอนนี้",
        hello: "สวัสดี", guest: "แขก", search_placeholder: "ค้นหาที่พัก...", homepage: "หน้าแรก", profile: "โปรไฟล์",
        saved: "บันทึกแล้ว", my_listings: "ที่พักของฉัน", chats: "แชท",
        edit_profile: "แก้ไขโปรไฟล์", display_name: "ชื่อที่แสดง", bio: "ประวัติส่วนตัว",
        change_limit: "เปลี่ยนได้ทุกๆ 30 วัน", bio_placeholder: "บอกอะไรบางอย่างเกี่ยวกับคุณ...",
        cancel: "ยกเลิก", save_changes: "บันทึกการเปลี่ยนแปลง", settings: "การตั้งค่า", accounts_center: "ศูนย์บัญชี",
        app_language: "ภาษาของแอป", help_support: "ความช่วยเหลือ", about: "เกี่ยวกับเรา", log_out: "ออกจากระบบ",
        uploading: "กำลังอัปโหลด...", edit_cover: "แก้ไขรูปภาพหน้าปก", welcome_home: "ยินดีต้อนรับกลับบ้าน",
        houses: "ที่พัก", view_details: "ดูรายละเอียด →", month_abbr: "/เดือน",
        add_property: "เพิ่มที่พัก", property_type: "ประเภทที่พัก", house: "บ้าน", commercial_space: "พื้นที่เชิงพาณิชย์", apartment: "อพาร์ทเมนท์", condominium: "คอนโดมิเนียม", hotel: "โรงแรม", city: "เมือง", district: "เขต", address: "ที่อยู่", exact_location: "ตำแหน่งที่แน่นอน", drag_pin: "ลากหมุดไปยังตำแหน่งที่พักที่แน่นอน", price_vnd: "ราคา (VND)", area_m2: "พื้นที่ (ตร.ม.)", contact_phone: "เบอร์โทรศัพท์", photos: "รูปภาพ", videos: "วิดีโอ", upload: "อัปโหลด", click_add_photos: "คลิกเพื่อเพิ่มรูปภาพ (ไม่เกิน 7 รูป)",
        click_add_videos: "คลิกเพื่อเพิ่มวิดีโอ (ไม่เกิน 2 วิดีโอ)",
        ward: "แขวง/ตำบล",
        street_address: "ที่อยู่โดยละเอียด (เลขที่บ้าน, ซอย, ถนน)",
        use_current_location: "ใช้ตำแหน่งปัจจุบัน",
        geocoding_loading: "กำลังค้นหาตำแหน่ง...",
        submit_property: "ส่งข้อมูล", submitting_property: "กำลังดำเนินการ...", submitted_success: "ส่งข้อมูลสำเร็จ", submitted_failed: "ส่งข้อมูลล้มเหลว", try_again: "ลองใหม่", login_to_add: "กรุณาเข้าสู่ระบบเพื่อเพิ่มที่พัก", uploading_cloud: "กำลังอัปโหลด...",
        tour_step1_title: "ค้นหาที่พักบนแผนที่", tour_step1_desc: "หน้าแรกแสดงที่พักให้เช่าทั้งหมดผ่านแผนที่",
        tour_step2_title: "เครื่องหมายบนแผนที่", tour_step2_desc: "แต่ละหมุดแสดงที่พัก คลิกเพื่อดูรายละเอียด",
        tour_step3_title: "แถบค้นหา", tour_step3_desc: "ใช้แถบค้นหาเพื่อค้นหาที่พักตามสถานที่",
        tour_step4_title: "ตัวกรอง", tour_step4_desc: "ใช้ตัวกรองเพื่อค้นหาตามราคา ประเภท ฯลฯ",
        tour_step5_title: "โพสต์ประกาศใหม่", tour_step5_desc: "คลิกที่นี่เพื่อโพสต์ประกาศเช่าใหม่",
        tour_done_title: "พร้อมแล้ว! 🎉", tour_done_desc: "คุณพร้อมที่จะค้นหาและโพสต์ที่พักแล้ว!",
        tour_skip: "ข้าม", tour_next: "ถัดไป", tour_finish: "เริ่มเลย",
        login_title: "ยินดีต้อนรับกลับมา",
        login_subtitle: "เข้าสู่ระบบเพื่อค้นหาที่พักต่อไป",
        email_username_placeholder: "อีเมลหรือชื่อผู้ใช้",
        password_placeholder: "รหัสผ่าน",
        sign_in_btn: "เข้าสู่ระบบ",
        signing_in: "กำลังเข้าสู่ระบบ...",
        no_account: "ยังไม่มีบัญชีใช่ไหม?",
        create_one: "สร้างบัญชีใหม่",
        register_title: "สร้างบัญชีของคุณ",
        register_subtitle: "เข้าร่วมกับผู้เช่านับพันวันนี้",
        full_name_placeholder: "ชื่อ-นามสกุล",
        username_placeholder: "ชื่อผู้ใช้",
        email_placeholder: "อีเมล",
        phone_placeholder: "เบอร์โทรศัพท์",
        confirm_password_placeholder: "ยืนยันรหัสผ่าน",
        create_account_btn: "สร้างบัญชี",
        creating_account: "กำลังสร้าง...",
        already_have_account: "มีบัญชีอยู่แล้ว?",
        sign_in_link: "เข้าสู่ระบบ",
        hero_login_title: "ค้นหาบ้านเช่าหลังถัดไปของคุณ",
        hero_login_desc: "เรียกดูประกาศนับพันที่ผ่านการตรวจสอบแล้ว",
        hero_register_title: "เริ่มต้นการเดินทางสู่บ้านที่สมบูรณ์แบบ",
        hero_register_desc: "สร้างบัญชีเพื่อบันทึกรายการโปรดและติดต่อเจ้าของ",
        logo_subtitle: "ค้นหาสถานที่ที่สมบูรณ์แบบของคุณ",
        err_enter_email_username: "กรุณาใส่อีเมลหรือชื่อผู้ใช้",
        err_enter_password: "กรุณาใส่รหัสผ่าน",
        err_login_failed: "การเข้าสู่ระบบล้มเหลว ลองอีกครั้ง",
        err_enter_full_name: "กรุณาใส่ชื่อ-นามสกุลของคุณ",
        err_enter_username: "กรุณาใส่ชื่อผู้ใช้",
        err_username_length: "ชื่อผู้ใช้ต้องมีอย่างน้อย 3 ตัวอักษร",
        err_enter_email: "กรุณาใส่อีเมลของคุณ",
        err_invalid_email: "รูปแบบอีเมลไม่ถูกต้อง",
        err_enter_phone: "กรุณาใส่เบอร์โทรศัพท์",
        err_confirm_password: "กรุณายืนยันรหัสผ่าน",
        err_passwords_mismatch: "รหัสผ่านไม่ตรงกัน",
        err_complete_captcha: "กรุณากรอกรหัสความปลอดภัย",
        password_requirements: "ข้อกำหนดของรหัสผ่าน:",
        rule_length: "8-12 ตัวอักษร",
        rule_uppercase: "อักษรตัวใหญ่ (A-Z)",
        rule_lowercase: "อักษรตัวเล็ก (a-z)",
        rule_number: "ตัวเลข (0-9)",
        rule_special: "อักขระพิเศษ (@$!%*?&)",
        last_name: "นามสกุล", first_name: "ชื่อ", personal_info: "ข้อมูลส่วนตัว", security_settings: "ความปลอดภัยและรหัสผ่าน",
        current_password: "รหัสผ่านปัจจุบัน", new_password: "รหัสผ่านใหม่", confirm_new_password: "ยืนยันรหัสผ่านใหม่",
        update_password: "อัปเดตรหัสผ่าน", email_label: "อีเมล", profile_updated_success: "อัปเดตโปรไฟล์สำเร็จ!",
        password_updated_success: "เปลี่ยนรหัสผ่านสำเร็จ!", account_privacy_title: "บัญชีและความปลอดภัย",
        account_privacy_desc: "จัดการข้อมูลส่วนตัวและการตั้งค่าความปลอดภัยที่นี่",
        help_title: "ศูนย์ช่วยเหลือ", help_subtitle: "เราจะช่วยคุณได้อย่างไรในวันนี้?",
        faq_title: "คำถามที่พบบ่อย", faq_q1: "ฉันจะโพสต์ประกาศได้อย่างไร?", faq_a1: "เพียงคลิกปุ่ม + ในหน้าแรกหรือในโปรไฟล์ของคุณ",
        contact_us: "ติดต่อเรา", contact_email: "ฝ่ายสนับสนุนทางอีเมล", contact_chat: "แชทสด", contact_call: "สายด่วน",
        profile_tab: "โปรไฟล์", post_listing_tab: "ประกาศ",
        saved_properties: "ที่พักที่บันทึกไว้", no_saved_properties: "ไม่มีที่พักที่บันทึกไว้",
        save_properties_hint: "แตะไอคอนหัวใจบนที่พักเพื่อบันทึกที่นี่",
        my_listings_title: "ประกาศของฉัน", no_listings_yet: "ยังไม่มีประกาศ",
        add_listing_hint: "ใช้ปุ่ม + ด้านล่างเพื่อเพิ่มที่พักแรกของคุณ",
        display_mode: "โหมดการแสดงผล", price: "ราคา"
    },
    id: {
        loading: "Memuat...", no_info: "Informasi properti tidak ditemukan.", go_back: "Kembali",
        available: "Tersedia", rented: "Disewakan", million: "juta", vnd_per_month: "VND / bulan",
        posted_by: "Diposting oleh", no_poster_info: "Tidak ada info pemasang", bedrooms: "Kamar Tidur",
        private_bath: "Pribadi", shared_bath: "Bersama", bathrooms: "Kamar Mandi", area: "Luas",
        description: "Deskripsi", no_description: "Tidak ada deskripsi.", contact_now: "Hubungi Sekarang",
        hello: "Halo", guest: "Tamu", search_placeholder: "Cari properti...", homepage: "Beranda", profile: "Profil",
        saved: "Simpan", my_listings: "Iklan Saya", chats: "Chat",
        edit_profile: "Edit Profil", display_name: "Nama Tampilan", bio: "Bio",
        change_limit: "Batas perubahan: Sekali setiap 30 hari.", bio_placeholder: "Ceritakan sedikit tentang dirimu...",
        cancel: "Batal", save_changes: "Simpan Perubahan", settings: "Pengaturan", accounts_center: "Pusat Akun",
        app_language: "Bahasa Aplikasi", help_support: "Bantuan & Dukungan", about: "Tentang", log_out: "Keluar",
        uploading: "Mengunggah...", edit_cover: "Edit Foto Sampul", welcome_home: "Selamat Datang di Rumah",
        houses: "properti", view_details: "Lihat detail →", month_abbr: "/bln",
        add_property: "Tambah Properti", property_type: "Tipe Properti", house: "Rumah", commercial_space: "Ruang Komersial", apartment: "Apartemen", condominium: "Kondominium", hotel: "Hotel", city: "Kota", district: "Distrik", address: "Alamat", exact_location: "Lokasi Tepat", drag_pin: "Geser pin ke lokasi properti yang tepat", price_vnd: "Harga (VND)", area_m2: "Luas (m²)", contact_phone: "Telepon Kontak", photos: "Foto", videos: "Video", upload: "Unggah", click_add_photos: "Klik untuk tambah foto (maks 7)",
        click_add_videos: "Klik untuk tambah video (maks 2)",
        ward: "Kelurahan/Kecamatan",
        street_address: "Alamat Lengkap (No rumah, gang, nama jalan)",
        use_current_location: "Gunakan lokasi saat ini",
        geocoding_loading: "Mencari lokasi...",
        submit_property: "Kirim Properti", submitting_property: "Mengirim...", submitted_success: "Properti berhasil dikirim", submitted_failed: "Gagal mengirim properti", try_again: "Coba Lagi", login_to_add: "Silakan login untuk menambah", uploading_cloud: "Mengunggah media ke Cloudinary...",
        tour_step1_title: "Temukan Sewaan di Peta", tour_step1_desc: "Beranda menampilkan semua properti sewa melalui peta interaktif kami.",
        tour_step2_title: "Penanda Properti", tour_step2_desc: "Setiap penanda mewakili iklan sewa. Ketuk penanda untuk lihat detail.",
        tour_step3_title: "Kolom Pencarian", tour_step3_desc: "Gunakan kolom pencarian untuk mencari berdasarkan lokasi.",
        tour_step4_title: "Filter", tour_step4_desc: "Gunakan filter untuk mempersempit iklan berdasarkan harga, tipe, dll.",
        tour_step5_title: "Pasang Iklan Baru", tour_step5_desc: "Klik di sini untuk memasang iklan sewa baru.",
        tour_done_title: "Selesai! 🎉", tour_done_desc: "Anda siap untuk mulai menjelajah dan memasang iklan!",
        tour_skip: "Lewati", tour_next: "Berikutnya", tour_finish: "Mulai",
        login_title: "Selamat datang kembali",
        login_subtitle: "Masuk untuk lanjut mencari rumah sewa",
        email_username_placeholder: "Email atau username",
        password_placeholder: "Kata sandi",
        sign_in_btn: "Masuk",
        signing_in: "Masuk...",
        no_account: "Belum punya akun?",
        create_one: "Buat akun",
        register_title: "Buat akun Anda",
        register_subtitle: "Bergabunglah dengan ribuan penyewa bahagia",
        full_name_placeholder: "Nama lengkap",
        username_placeholder: "Username",
        email_placeholder: "Alamat email",
        phone_placeholder: "Nomor telepon",
        confirm_password_placeholder: "Konfirmasi kata sandi",
        create_account_btn: "Buat Akun",
        creating_account: "Membuat...",
        already_have_account: "Sudah punya akun?",
        sign_in_link: "Masuk",
        hero_login_title: "Temukan rumah sewa Anda berikutnya",
        hero_login_desc: "Cari ribuan iklan terverifikasi dan temukan ruang yang tepat.",
        hero_register_title: "Mulai perjalanan menuju rumah impian",
        hero_register_desc: "Buat akun untuk simpan favorit dan hubungi pemilik.",
        logo_subtitle: "Temukan tempat ideal Anda",
        err_enter_email_username: "Silakan masukkan email atau username",
        err_enter_password: "Silakan masukkan kata sandi",
        err_login_failed: "Gagal masuk. Silakan coba lagi.",
        err_enter_full_name: "Silakan masukkan nama lengkap Anda",
        err_enter_username: "Silakan masukkan username",
        err_username_length: "Username minimal 3 karakter",
        err_enter_email: "Silakan masukkan email Anda",
        err_invalid_email: "Format email tidak valid",
        err_enter_phone: "Silakan masukkan nomor telepon",
        err_confirm_password: "Silakan konfirmasi kata sandi",
        err_passwords_mismatch: "Kata sandi tidak cocok",
        err_complete_captcha: "Silakan selesaikan captcha",
        password_requirements: "Persyaratan kata sandi:",
        rule_length: "8-12 karakter",
        rule_uppercase: "Huruf besar (A-Z)",
        rule_lowercase: "Huruf kecil (a-z)",
        rule_number: "Angka (0-9)",
        rule_special: "Karakter khusus (@$!%*?&)",
        last_name: "Nama Belakang", first_name: "Nama Depan", personal_info: "Informasi Pribadi", security_settings: "Keamanan & Kata Sandi",
        current_password: "Kata Sandi Saat Ini", new_password: "Kata Sandi Baru", confirm_new_password: "Konfirmasi Kata Sandi Baru",
        update_password: "Perbarui Kata Sandi", email_label: "Alamat Email", profile_updated_success: "Profil berhasil diperbarui!",
        password_updated_success: "Kata sandi berhasil diubah!", account_privacy_title: "Akun & Keamanan",
        account_privacy_desc: "Kelola detail pribadi dan pengaturan keamanan akun Anda di sini.",
        help_title: "Pusat Bantuan", help_subtitle: "Ada yang bisa kami bantu?",
        faq_title: "Tanya Jawab", faq_q1: "Bagaimana cara pasang iklan?", faq_a1: "Cukup klik tombol + di halaman utama atau di profil Anda.",
        contact_us: "Hubungi Kami", contact_email: "Dukungan Email", contact_chat: "Chat Langsung", contact_call: "Hotline",
        profile_tab: "Profil", post_listing_tab: "Pasang",
        saved_properties: "Properti Disimpan", no_saved_properties: "Belum ada properti disimpan",
        save_properties_hint: "Ketuk ikon hati di properti mana pun untuk menyimpan.",
        my_listings_title: "Iklan Saya", no_listings_yet: "Belum ada iklan",
        add_listing_hint: "Gunakan tombol + di bawah untuk tambah properti pertama.",
        display_mode: "Mode Tampilan", price: "Harga"
    },
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: keyof typeof dictionaries.vi) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>("vi");

    useEffect(() => {
        const savedLang = localStorage.getItem("app_lang") as Language;
        if (savedLang && dictionaries[savedLang]) {
            setLanguageState(savedLang);
            return;
        }

        const countryToLang: Record<string, Language> = {
            VN: "vi", US: "en", GB: "en", AU: "en", CA: "en", NZ: "en", IE: "en", SG: "en", PH: "en", IN: "en", ZA: "en",
            MY: "en", HK: "zh-TW", MO: "zh-TW", TW: "zh-TW", CN: "zh",
            ES: "es", MX: "es", AR: "es", CO: "es", PE: "es", CL: "es", VE: "es", EC: "es", BO: "es", UY: "es",
            FR: "fr", BE: "fr", CH: "fr", LU: "fr", MC: "fr",
            KR: "ko", JP: "ja", TH: "th", ID: "id",
        };

        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 3000);

        fetch("https://ipapi.co/json/", { signal: controller.signal })
            .then(r => r.json())
            .then((data: { country_code?: string }) => {
                clearTimeout(timeoutId);
                const detected = data.country_code ? countryToLang[data.country_code] : undefined;
                let lang: Language = detected || (data.country_code === "VN" ? "vi" : "en");
                setLanguageState(lang);
                localStorage.setItem("app_lang", lang);
            })
            .catch(() => {
                setLanguageState("en"); 
                localStorage.setItem("app_lang", "en");
            });

        return () => { clearTimeout(timeoutId); controller.abort(); };
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("app_lang", lang);
    };

    const t = (key: keyof typeof dictionaries.vi): string => {
        return dictionaries[language]?.[key] || dictionaries.vi[key] || (key as string);
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage(): LanguageContextType {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        return { language: "vi", setLanguage: () => { }, t: (key) => String(key) };
    }
    return context;
}
